[package]
name = "waiting_thread_hijacking"
version = "0.1.0"
edition = "2024"

[dependencies]
ntapi = "0.4.1"
winapi = { version = "0.3.9", features = ["processthreadsapi","memoryapi","libloaderapi"]} 