[package]
name = "process_ghosting"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "fileapi", "errhandlingapi", "winbase", "memoryapi", "processenv", "userenv","handleapi", "winnt" ] }
ntapi = "0.4.1"